# Generated by Django 4.0.2 on 2022-02-28 18:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academicien',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('matricule', models.CharField(max_length=6, unique=True)),
                ('nom', models.CharField(max_length=255)),
                ('prenoms', models.CharField(max_length=255)),
                ('date', models.DateField(default=datetime.date(2022, 2, 28))),
                ('photo', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'academicien',
            },
        ),
        migrations.CreateModel(
            name='Motif',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('motif', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('date', models.DateField(default=datetime.date(2022, 2, 28))),
            ],
            options={
                'db_table': 'motif',
            },
        ),
        migrations.CreateModel(
            name='Payement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date(2022, 2, 28))),
                ('montant', models.BigIntegerField(default=True)),
                ('status', models.BooleanField(default=True)),
                ('id_academicien', models.ForeignKey(db_column='id_academicien', on_delete=django.db.models.deletion.CASCADE, related_name='id_academicien', to='api.academicien')),
                ('id_motif', models.ForeignKey(db_column='id_motif', on_delete=django.db.models.deletion.CASCADE, related_name='id_motif', to='api.motif')),
            ],
            options={
                'db_table': 'payement',
            },
        ),
    ]
