# Generated by Django 4.0.2 on 2022-03-02 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicien',
            name='date',
            field=models.DateField(default=datetime.date(2022, 3, 2)),
        ),
        migrations.AlterField(
            model_name='motif',
            name='date',
            field=models.DateField(default=datetime.date(2022, 3, 2)),
        ),
        migrations.AlterField(
            model_name='payement',
            name='date',
            field=models.DateField(default=datetime.date(2022, 3, 2)),
        ),
    ]
