# Generated by Django 4.0.2 on 2022-02-28 18:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_academicien_sommetotalpaieyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicien',
            name='sommeTotalPaieyer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
