# Generated by Django 4.0.2 on 2022-03-02 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_motif_motif_libelle_motif'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motif',
            old_name='status',
            new_name='statut',
        ),
    ]
